### PR TITLE
Run shell script command fix for windows

### PR DESCRIPTION
**Pull request by dineshrivankar**
* **What kind of change does this PR introduce (Bug fix, feature, docs update, ...)?**
  Bug fix

* **What is the current behavior?**
  Dev environment setup on windows system gives error for setup script.

* **What is the new behavior (if this is a feature change)?**
  Dev enviroment setup for windows is fixed by invoking the shell script with sh command. 

* **Does this PR introduce a breaking change? If so, what actions will users need to take in order to regain compatibility?**
  If the PR brakes, then just change remove sh prefix from the run_command() 

### All submissions

* [Y] Have you followed the guidelines in our [Contributing](CONTRIBUTING.md) document?
* [N] Is this PR targeting the `develop` branch, and the branch rebased with commits squashed if needed?
* [Y] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

### New feature and bug fix submissions

* [Y] Has your submission been tested locally?
* [N] Has documentation such as the [README](/README.md) been updated if necessary?
* [Y] Have you linted your new code (using rubocop and markdownlint), and are not introducing any new offenses?

### CODE REVIEW

**Comment by sdchapman** [comment]
Thanks. What Windows shell did you find you needed this change for - Git Bash, or a WSL shell like Ubuntu?

The develop branch has many Windows-related fixes in it although Ruby running through Git Bash still has trouble with sh files, I'm wondering if this would fix that.

**Comment by dineshrivankar** [comment]
Hi,

I used git bash as a terminal, one thing to know here is we need to switch docker to Linux container mode.

In Windows the root path starts with drive name eg D:\ which is an formatting issue.

**Comment by sdchapman** [comment]
Your changes seemed to fix the last remaining problem I was encountering with Git Bash, excellent!

Because this PR is targeting master, and I have made significant changes in develop that would make merging a bit tricky, I'm going to close this PR, but rest assured your changes are integrated, and will be in the next release.

I have created a wiki page with suggestions for getting Windows fully working which will apply to the next release - https://github.com/LandRegistry/common-dev-env/wiki/Windows-setup

**Comment by dineshrivankar** [comment]
Thanks @sdchapman

**Pull request closed without merging**
